server:
  port: 8086

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8082}
management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 0.1