spring:
  datasource:
    url: ${DB_URL:}
    username: ${DB_USER:}
    password: ${DB_PASS:}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:}
    consumer:
      group-id: trade-ms-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8085

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:${CORS_ALLOWED_ORIGIN:http://localhost:3000}}

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 0.1
  logging:
    minimum-breadcrumb-level: info
    minimum-event-level: error

feign:
  client:
    config:
      default:
        connectTimeout: 3000 # Bağlantı üçün 3 saniyə gözlə
        readTimeout: 5000    # Datanı oxumaq üçün 5 saniyə gözlə
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      price-ms: # @FeignClient(name = "price-ms") ilə eyni adda olmalıdır
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3